### ISSUE TITLE
inaccurate radiometric data - Jetson Nano & Lepton 3.5

### ISSUE THREAD

**Issue by sethuageye** [Myzhar/Lepton3_Jetson#12]
Greetings!!
Thanks for this contribution. Helped a lot!

I am using Jetson Nano with Jetpack 4.6 and Flir Lepton 3.5.
Need to get radiometric temperature values from Lepton 3.5.
Enabled SPI (buffer size 20480) and both the applications "Check Fever APP" and "OpenCV demo" are able to stream thermal image.

As my requirement is radiometric temperature values, I have enabled radiometry and configured the device to "high gain" mode. 

Used "opencv demo", "fever_check_app" project and printed the 16-bit values from the API "getLastFrame16".
Converted the values to temperature using the scaling factor used by the author (0.0092 - high gain mode - temperature range -10 C to 140 C, as mentioned in datasheet).

Temperature value for human subjects seemed accurate. But, when i tried to measure objects whose temperature range is between 10 C to 15 C, the resultant radiometric values were wrong, it showed 24 - 29 C. (both opencv_demo & check_fever_app)

**Code snippet added to opencv demo:**

uint16_t x1;
for(x1=0;x1<(w*h);x1++)
{
    cout << " " << data16[x1]*0.0092;
}
// data 16 is a uint16_t pointer which gets data from getLastFrame16() API in the original code
**These are the only modifications made to the codes.**

Was able to read lower temperatures such as 10C with another python wrapper in Rpi4 (https://github.com/groupgets/pylepton)

Tried low gain mode also, no improvement. Should I make any additional configurations . Is there anything I am missing out?

How could I improve the accuracy of the Lepton 3.5 throughout its range (-10C to 140C)?

Kindly suggest. Thanks in advance!!

**Comment by Myzhar** [comment]
If you have a radiometric sensor you should exploit this feature and no calibration is required.
You can read more in chapter 3.5.1 of the datasheet:
[500-0659-00-09 Rev204 Lepton Engineering Datasheet.pdf](https://github.com/Myzhar/Lepton3_Jetson/files/7847597/500-0659-00-09.Rev204.Lepton.Engineering.Datasheet.pdf)
My driver does not support it because I have a Lepton 3.0 that has not radiometry, but I suppose that you can easily modify it.

You must modify this function to be sure that you are using the `TLinear` feature:
https://github.com/Myzhar/Lepton3_Jetson/blob/master/grabber_lib/src/Lepton3.cpp#L777-L805
